acme_bug_homepage:
    path:     /hello/{name}
    defaults: { _controller: AcmeBugBundle:Default:index }

main:
    path:     /main
    defaults: { _controller: AcmeBugBundle:User:registration }

project:
    path: /project
    defaults: {_controller: AcmeBugBundle:Project:project }

project_create:
    path: /project_create
    defaults: {_controller: AcmeBugBundle:Project:project_create }

project_edit:
     path: /project_edit
     defaults: {_controller: AcmeBugBundle:Project:project_edit }

issue:
    path: /issue
    defaults: {_controller: AcmeBugBundle:Issue:issue }

main_activity:
    path: /main
    defaults: {_controller: AcmeBugBundle:Registration:confirm }

profile:
    path: /profile
    defaults: {_controller: AcmeBugBundle:User:profile }

project_page:
    path: /project/{code}
    defaults: {_controller: AcmeBugBundle:Project:project_code  }
