login:
    path:     /login
    defaults: { _controller: AcmeBugBundle:Security:login }

register:
    path:   /register
    defaults: { _controller: AcmeBugBundle:Registration:register }

project:
    path: /project
    defaults: {_controller: AcmeBugBundle:Project:project }

project_create:
    path: /project_create
    defaults: {_controller: AcmeBugBundle:Project:project_create }

project_edit:
     path: /project_edit
     defaults: {_controller: AcmeBugBundle:Project:project_edit }

issue:
    path: /issue
    defaults: {_controller: AcmeBugBundle:Issue:issue }

main:
    path: /
    defaults: {_controller: AcmeBugBundle:Home:home }

profile:
    path: /profile
    defaults: {_controller: AcmeBugBundle:User:profile }

project_page:
    path: /project/{code}
    defaults: {_controller: AcmeBugBundle:Project:project_code  }

issue_page:
    path: /issue/{code}
    defaults: {_controller: AcmeBugBundle:Issue:issue_code  }

issue_create:
    path: /issue_create
    defaults: {_controller: AcmeBugBundle:Issue:issue_create }

issue_edit:
     path: /issue_edit/{code}
     defaults: {_controller: AcmeBugBundle:Issue:issue_edit }

admin:
    path: /admin
    defaults: {_controller: AcmeBugBundle:Admin:admin }

admin_user_view:
    path: /admin/{id}
    defaults: {_controller: AcmeBugBundle:Admin:viewuser}

edit_profile:
    path: /admin/{id}/edit_profile
    defaults: {_controller: AcmeBugBundle:Admin:editprofile }

issue_comment:
    path: /issue/{code}/comment
    defaults: {_controller: AcmeBugBundle:Issue:addComment }

profile_edit:
    path: /profile/edit
    defaults: {_controller: AcmeBugBundle:User:profile_edit }
