services:
#    acme_bug.example:
#        class: Acme\BugBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
 app.form.registration:
        class:         Acme\BugBundle\Form\RegistrationType
        tags:
                      - { name: form.type, alias: app_user_registration }

 form.project.registration:
        class:   Acme\BugBundle\Form\Type\ProjectType
        tags:
                - { name: form.type, alias: form_project_registration }

 form.issue.registration:
         class:   Acme\BugBundle\Form\Type\IssueType
         tags:
                 - { name: form.type, alias: form_issue_registration }

 project:
      class:   Acme\BugBundle\Entity\Project

 issue:
      class:  Acme\BugBundle\Entity\Issue

 helper:
      class:   Acme\BugBundle\Entity\Helper
      arguments: ["project","issue"]