services:
#    acme_bug.example:
#        class: Acme\BugBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    bug.form.registration:
        class:                Acme\BugBundle\Form\RegistrationType
        tags:
                            - { name: form.type, alias: bug_user_registration }


